name: Release

on:
  push:
    branches:
      - 'feat/release-workflow' # TODO: Put back to tags when ready
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Add GOBIN to PATH
      run: echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        # Needed for release notes
        fetch-depth: 0

    - name: Publish Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.DEV_TOOLKIT_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        SNAPCRAFT_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
      run: make release-publish
